version: "3.8"

services:
  backend:
    image: ghcr.io/poly-prompt-team-7/backend-placeholder:latest
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/tmp
    env_file:
      - .env

  frontend:
    image: ghcr.io/poly-prompt-team-7/kg-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      API_URL: "http://backend:8000"
