services:
  backend:
    image: ghcr.io/poly-prompt-team-7/backend-placeholder:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENALEX_API_KEY=${OPENALEX_API_KEY}
      - CANVAS_API_KEY=${CANVAS_API_KEY}
  frontend:
    build:
      context: ../frontendv2
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
